// Generated by gencpp from file pmt/pmtsrvRequest.msg
// DO NOT EDIT!


#ifndef PMT_MESSAGE_PMTSRVREQUEST_H
#define PMT_MESSAGE_PMTSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pmt
{
template <class ContainerAllocator>
struct pmtsrvRequest_
{
  typedef pmtsrvRequest_<ContainerAllocator> Type;

  pmtsrvRequest_()
    : A(0)
    , B(0)
    , C(0)  {
    }
  pmtsrvRequest_(const ContainerAllocator& _alloc)
    : A(0)
    , B(0)
    , C(0)  {
  (void)_alloc;
    }



   typedef int32_t _A_type;
  _A_type A;

   typedef int32_t _B_type;
  _B_type B;

   typedef int32_t _C_type;
  _C_type C;





  typedef boost::shared_ptr< ::pmt::pmtsrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pmt::pmtsrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct pmtsrvRequest_

typedef ::pmt::pmtsrvRequest_<std::allocator<void> > pmtsrvRequest;

typedef boost::shared_ptr< ::pmt::pmtsrvRequest > pmtsrvRequestPtr;
typedef boost::shared_ptr< ::pmt::pmtsrvRequest const> pmtsrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pmt::pmtsrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pmt::pmtsrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pmt::pmtsrvRequest_<ContainerAllocator1> & lhs, const ::pmt::pmtsrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.A == rhs.A &&
    lhs.B == rhs.B &&
    lhs.C == rhs.C;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pmt::pmtsrvRequest_<ContainerAllocator1> & lhs, const ::pmt::pmtsrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pmt

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pmt::pmtsrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pmt::pmtsrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pmt::pmtsrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pmt::pmtsrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pmt::pmtsrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pmt::pmtsrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pmt::pmtsrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e7a68ce4e0b75a9719b4950a7069c9d4";
  }

  static const char* value(const ::pmt::pmtsrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe7a68ce4e0b75a97ULL;
  static const uint64_t static_value2 = 0x19b4950a7069c9d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::pmt::pmtsrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pmt/pmtsrvRequest";
  }

  static const char* value(const ::pmt::pmtsrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pmt::pmtsrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 A\n"
"int32 B\n"
"int32 C\n"
;
  }

  static const char* value(const ::pmt::pmtsrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pmt::pmtsrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.A);
      stream.next(m.B);
      stream.next(m.C);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pmtsrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pmt::pmtsrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pmt::pmtsrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "A: ";
    Printer<int32_t>::stream(s, indent + "  ", v.A);
    s << indent << "B: ";
    Printer<int32_t>::stream(s, indent + "  ", v.B);
    s << indent << "C: ";
    Printer<int32_t>::stream(s, indent + "  ", v.C);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PMT_MESSAGE_PMTSRVREQUEST_H
