// Generated by gencpp from file pmt/pmtsrv.msg
// DO NOT EDIT!


#ifndef PMT_MESSAGE_PMTSRV_H
#define PMT_MESSAGE_PMTSRV_H

#include <ros/service_traits.h>


#include <pmt/pmtsrvRequest.h>
#include <pmt/pmtsrvResponse.h>


namespace pmt
{

struct pmtsrv
{

typedef pmtsrvRequest Request;
typedef pmtsrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pmtsrv
} // namespace pmt


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pmt::pmtsrv > {
  static const char* value()
  {
    return "dcb5cd4885c92b4d86b7f754d9c5db05";
  }

  static const char* value(const ::pmt::pmtsrv&) { return value(); }
};

template<>
struct DataType< ::pmt::pmtsrv > {
  static const char* value()
  {
    return "pmt/pmtsrv";
  }

  static const char* value(const ::pmt::pmtsrv&) { return value(); }
};


// service_traits::MD5Sum< ::pmt::pmtsrvRequest> should match
// service_traits::MD5Sum< ::pmt::pmtsrv >
template<>
struct MD5Sum< ::pmt::pmtsrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pmt::pmtsrv >::value();
  }
  static const char* value(const ::pmt::pmtsrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pmt::pmtsrvRequest> should match
// service_traits::DataType< ::pmt::pmtsrv >
template<>
struct DataType< ::pmt::pmtsrvRequest>
{
  static const char* value()
  {
    return DataType< ::pmt::pmtsrv >::value();
  }
  static const char* value(const ::pmt::pmtsrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pmt::pmtsrvResponse> should match
// service_traits::MD5Sum< ::pmt::pmtsrv >
template<>
struct MD5Sum< ::pmt::pmtsrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pmt::pmtsrv >::value();
  }
  static const char* value(const ::pmt::pmtsrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pmt::pmtsrvResponse> should match
// service_traits::DataType< ::pmt::pmtsrv >
template<>
struct DataType< ::pmt::pmtsrvResponse>
{
  static const char* value()
  {
    return DataType< ::pmt::pmtsrv >::value();
  }
  static const char* value(const ::pmt::pmtsrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PMT_MESSAGE_PMTSRV_H
