// Generated by gencpp from file pmt/vec.msg
// DO NOT EDIT!


#ifndef PMT_MESSAGE_VEC_H
#define PMT_MESSAGE_VEC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pmt
{
template <class ContainerAllocator>
struct vec_
{
  typedef vec_<ContainerAllocator> Type;

  vec_()
    : x()  {
    }
  vec_(const ContainerAllocator& _alloc)
    : x(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _x_type;
  _x_type x;





  typedef boost::shared_ptr< ::pmt::vec_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pmt::vec_<ContainerAllocator> const> ConstPtr;

}; // struct vec_

typedef ::pmt::vec_<std::allocator<void> > vec;

typedef boost::shared_ptr< ::pmt::vec > vecPtr;
typedef boost::shared_ptr< ::pmt::vec const> vecConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pmt::vec_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pmt::vec_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pmt::vec_<ContainerAllocator1> & lhs, const ::pmt::vec_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pmt::vec_<ContainerAllocator1> & lhs, const ::pmt::vec_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pmt

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pmt::vec_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pmt::vec_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pmt::vec_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pmt::vec_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pmt::vec_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pmt::vec_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pmt::vec_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c5012a429e390f4ddcf2e02fa7cb0fc8";
  }

  static const char* value(const ::pmt::vec_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc5012a429e390f4dULL;
  static const uint64_t static_value2 = 0xdcf2e02fa7cb0fc8ULL;
};

template<class ContainerAllocator>
struct DataType< ::pmt::vec_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pmt/vec";
  }

  static const char* value(const ::pmt::vec_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pmt::vec_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] x\n"
;
  }

  static const char* value(const ::pmt::vec_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pmt::vec_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vec_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pmt::vec_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pmt::vec_<ContainerAllocator>& v)
  {
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.x[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PMT_MESSAGE_VEC_H
