// Generated by gencpp from file action_pmt/demoFeedback.msg
// DO NOT EDIT!


#ifndef ACTION_PMT_MESSAGE_DEMOFEEDBACK_H
#define ACTION_PMT_MESSAGE_DEMOFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace action_pmt
{
template <class ContainerAllocator>
struct demoFeedback_
{
  typedef demoFeedback_<ContainerAllocator> Type;

  demoFeedback_()
    : current_count(0)  {
    }
  demoFeedback_(const ContainerAllocator& _alloc)
    : current_count(0)  {
  (void)_alloc;
    }



   typedef int32_t _current_count_type;
  _current_count_type current_count;





  typedef boost::shared_ptr< ::action_pmt::demoFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_pmt::demoFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct demoFeedback_

typedef ::action_pmt::demoFeedback_<std::allocator<void> > demoFeedback;

typedef boost::shared_ptr< ::action_pmt::demoFeedback > demoFeedbackPtr;
typedef boost::shared_ptr< ::action_pmt::demoFeedback const> demoFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::action_pmt::demoFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::action_pmt::demoFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::action_pmt::demoFeedback_<ContainerAllocator1> & lhs, const ::action_pmt::demoFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.current_count == rhs.current_count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::action_pmt::demoFeedback_<ContainerAllocator1> & lhs, const ::action_pmt::demoFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace action_pmt

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::action_pmt::demoFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_pmt::demoFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_pmt::demoFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_pmt::demoFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_pmt::demoFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_pmt::demoFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::action_pmt::demoFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f77169e65b5b24a984cd3f9acb1e49b5";
  }

  static const char* value(const ::action_pmt::demoFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf77169e65b5b24a9ULL;
  static const uint64_t static_value2 = 0x84cd3f9acb1e49b5ULL;
};

template<class ContainerAllocator>
struct DataType< ::action_pmt::demoFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "action_pmt/demoFeedback";
  }

  static const char* value(const ::action_pmt::demoFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::action_pmt::demoFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"int32 current_count\n"
"\n"
;
  }

  static const char* value(const ::action_pmt::demoFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::action_pmt::demoFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct demoFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_pmt::demoFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::action_pmt::demoFeedback_<ContainerAllocator>& v)
  {
    s << indent << "current_count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.current_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTION_PMT_MESSAGE_DEMOFEEDBACK_H
